export declare enum MessageType {
  INIT = "INIT",
  DATASET = "DATASET",
  FUNCTION_RESPONSE = "FUNCTION_RESPONSE",
  FUNCTION_CALL = "FUNCTION_CALL",
  FILTER = "FILTER",
  FIX_CONFIGURATION = "FIX_CONFIGURATION",
  CONFIGURATION_OK = "CONFIGURATION_OK",
  READY = "READY",
}
//# sourceMappingURL=MessageType.d.ts.map
